### ISSUE TITLE
Support volume and volumeMounts 

### ISSUE THREAD

**Issue by nlu90** [streamnative/function-mesh-worker-service#159]
Function mesh allow user to set pod volumes and volumeMounts but the mesh worker service here doesn't support it.

We need to allow user provide additional volume and volumeMount info via customConfig(probably) to support this feature request.

**Comment by freeznet** [comment]
user can set `volume` and `volumeMount` here https://github.com/streamnative/function-mesh-worker-service/blob/master/src/main/java/io/functionmesh/compute/models/MeshWorkerServiceCustomConfig.java#L72-L80

**Comment by swani01** [comment]
This is not working at all, I have now tried everything but the mesh worker is simply not creating a k8s Function resource with the required volume/VolumeMount fields. Now using NAR file /pulsar/lib/mesh-worker-service-2.8.3.8.nar

It is also ignoring jobNamespace. All the other fields like  defaultResources are implemented

`    functionsWorkerServiceCustomConfigs:
      functionEnabled: true
      sinkEnabled: true
      sourceEnabled: true
      uploadEnabled: true
      volumeMounts:
        - mountPath: /mnt/efs
          name: shared-storage
          readOnly: false
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: efs-shared
      jobNamespace: pulsar-functions`

**Comment by freeznet** [comment]
@swani01 could you please provide the created function's resource in YAML? thanks.

**Comment by swani01** [comment]
Here it is one of them, as you can see k8s Namespace is wrong (it deploys in the ns where the function worker is running) and the volumes are missing.

`apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  creationTimestamp: "2022-08-30T15:32:02Z"
  generation: 1
  labels:
    appType: function
    functionmesh.io/managedBy: function-mesh
    pulsar-cluster: devpulsar
    pulsar-component: zone1_product_category
    pulsar-namespace: default
    pulsar-tenant: kevin
  name: zone1-product-category-b16e6e71
  namespace: pulsar
  resourceVersion: "5948573"
  uid: 535ffcac-5591-435e-ac20-913a9c097970
spec:
  autoAck: true
  className: com.cerebri.transform.impl.RowToTkvStation
  cleanupSubscription: true
  clusterName: devpulsar
  forwardSourceMessageProperty: false
  funcConfig:
    columnDelimiter: ','
    functionName: zone1_product_category
    oosEnabled: true
    rowIdentifier: ""
    tagLookup: "{\n  \"oneToOneMappings\" : {\n    \n  },\n  \"oneToManyMappings\"
      : {\n    \n  },\n  \"zeroToOneMappings\" : [\n    {\n      \"tagName\" : \"zone1_product_category.product\",\n
      \     \"handling\" : \"\",\n      \"link\" : null,\n      \"label\" : null,\n
      \     \"type\" : null,\n      \"tagRules\" : [\n      ],\n      \"ordered\"
      : true,\n      \"aspect\" : null\n    },\n    {\n      \"tagName\" : \"zone1_product_category.category\",\n
      \     \"handling\" : \"\",\n      \"link\" : null,\n      \"label\" : null,\n
      \     \"type\" : null,\n      \"tagRules\" : [\n      ],\n      \"ordered\"
      : true,\n      \"aspect\" : null\n    }\n  ],\n  \"oneToZeroMappings\" : [\n
      \ ]\n}"
  image: streamnative/pulsar-functions-java-runner:2.9.2.19
  input:
    sourceSpecs:
      persistent://kevin/default/timing_triggers.heartbeat: {}
      persistent://kevin/default/zone1_product_category.row: {}
    topics:
    - persistent://kevin/default/zone1_product_category.row
    - persistent://kevin/default/timing_triggers.heartbeat
    typeClassName: '[B'
  java:
    extraDependenciesDir: /pulsar/lib/
    jar: download/pulsar_functions/function-executable
    jarLocation: function://kevin/default/steamJarPackage@v1.0
  logTopic: persistent://kevin/default/zone1_product_category-log
  maxPendingAsyncRequests: 1000
  name: zone1-product-category-b16e6e71
  namespace: default
  output:
    producerConf: {}
    topic: persistent://kevin/default/zone1_product_category-out
    typeClassName: java.lang.Void
  pod:
    annotations:
      appType: function
    labels:
      appType: function
      functionmesh.io/managedBy: function-mesh
      pulsar-cluster: devpulsar
      pulsar-component: zone1_product_category
      pulsar-namespace: default
      pulsar-tenant: kevin
  processingGuarantee: atleast_once
  pulsar:
    pulsarConfig: devpulsar-function-mesh-config
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: "590558003"
    requests:
      cpu: 200m
      memory: "536870912"
  retainOrdering: true
  subscriptionPosition: latest
  tenant: kevin
status:
  conditions:
    Service:
      action: NoAction
      condition: ServiceReady
      status: "True"
    StatefulSet:
      action: Update
      condition: StatefulSetReady
      status: "False"
  replicas: 0
  selector: app=function-mesh,component=function,name=zone1-product-category-b16e6e71,namespace=pulsar`

**Comment by freeznet** [comment]
@swani01 thanks, we will check this one and get back to you later.

**Comment by swani01** [comment]
[util.zip](https://github.com/streamnative/function-mesh-worker-service/files/9653588/util.zip)
To speed things up a bit for you....

**Comment by freeznet** [comment]
close by https://github.com/streamnative/function-mesh-worker-service/pull/426
