### ISSUE TITLE
support `subscriptionPosition`/`subscriptionName` in Function, Sink

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh-worker-service#313]
the user submit functions using `--subs-position`, but the mesh worker service hasn't used the value when converting to CRs. 

- `functionDetails.getSource().getSubscriptionPosition()` 
- `functionDetails.getSource().getSubscriptionName()`

**Comment by jiangpengcheng** [comment]
I think `Source` doesn't have a relation with `subscriptionPosition`/`subscriptionName`?

**Comment by freeznet** [comment]
> I think `Source` doesn't have a relation with `subscriptionPosition`/`subscriptionName`?

correct, changed the title back.
