### ISSUE TITLE
fix MeshWorkerServiceStarter and allow use as standalone mode

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh-worker-service#38]

**Comment by freeznet** [comment]
The mesh worker service run with broker by default, but when the upgrade or update built-in connectors needs to taken in place, it requires to restart the broker, which will affect the pulsar cluster.

**Comment by jiangpengcheng** [comment]
function-mesh-worker-service can be ran in standalone mode using `bin/pulsar functions-worker` with `functionsWorkerServiceNarPackage` specified to the `mesh-worker-service.nar`, which will use the builtin worker service `WorkerServiceWithClassLoader` to load our `MeshWorkerService`

I think this is better than maintaining the `MeshWorkerServiceStarter` by ourselves, below are some benefits I think:

1. reduce duplicate code
2. always keep updated with the upstream

we can just write some documents about how to use it in standalone mode

**Comment by freeznet** [comment]
@jiangpengcheng make sense to me.
