### ISSUE TITLE
throw RestException SERVICE_UNAVAILABLE on non-supported rest APIs

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh-worker-service#638]
- [x] `stopFunctionInstance`
- [x] `startFunctionInstance`
- [x] `restartFunctionInstance`
- [x] `triggerFunction`
- [ ] `uploadFunction`
- [x] `downloadFunction`

**Comment by nlu90** [comment]
1. for `uploadFunction` and `downloadFunction`, we should ask users to use `packages` cmd.
2. for `triggerFunction`, we should say it's for debugging purpose and won't be supported.
3. for `stop`, `start`, `restart`, we may need to implement if necessary.

**Comment by jiangpengcheng** [comment]
except `uploadFunction`, all other APIs are implemented, and `uploadFunction` throws a `NOT_IMPLEMENTED` exception
