### ISSUE TITLE
add MANUAL processing guarantee

### ISSUE THREAD

**Issue by nlu90** [streamnative/function-mesh-worker-service#749]
There's a fourth processing guarantee called `MANUAL` added by the community

```
    --processing-guarantees
      The processing guarantees (aka delivery semantics) applied to the
      function #Java, Python, Go
      Possible Values: [ATLEAST_ONCE, ATMOST_ONCE, EFFECTIVELY_ONCE, MANUAL]
```

We need to support it here: 
https://github.com/streamnative/function-mesh-worker-service/blob/master/src/main/java/io/functionmesh/compute/util/CommonUtil.java#L194

https://github.com/streamnative/function-mesh-worker-service/blob/master/src/main/java/io/functionmesh/compute/util/CommonUtil.java#L206

**Comment by jiangpengcheng** [comment]
should wait for https://github.com/streamnative/function-mesh/pull/637 to be released
